/*
 * bitnet_main.c — minimal test program for the exported BitNet model
 * auto-generated by export_bitnet.py
 *
 * Build:  make
 * Run:    ./bitnet_test
 *
 * Expected behaviour: matches the Python model's prediction for the same input.
 * Python reference top-5: class 0=0.9105, class 22=0.0460, class 12=0.0140, class 30=0.0101, class 16=0.0096
 */

#include <stdio.h>
#include <string.h>
#include "bitnet_inference.h"
#include "bitnet_weights.h"

int main(void)
{
    printf("=== BitNet ESP32 Inference Test ===\n");
    printf("Architecture: [%d -> %d -> %d]  num_layers=%d\n",
           INPUT_SIZE, HIDDEN_SIZE, OUTPUT_SIZE, NUM_LAYERS);
    printf("Total ROM bytes: %d  (%.2f KB)\n\n",
           TOTAL_BYTES, (float)TOTAL_BYTES / 1024.0f);

    /* ---- Test input: one-hot encoding of class 0 (first letter / feature) ---- */
    float input[INPUT_SIZE] = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f };
    float output[OUTPUT_SIZE];

    printf("Input: one-hot[0] (first feature active, all others zero)\n");

    /* ---- Run inference ---- */
    bitnet_forward(input, output);

    /* ---- Report results ---- */
    int predicted = bitnet_argmax(output, OUTPUT_SIZE);
    printf("Predicted class: %d\n", predicted);
    printf("\nOutput probabilities:\n");
    for (int i = 0; i < OUTPUT_SIZE; ++i) {
        printf("  class %2d: %.6f%s\n",
               i, output[i], (i == predicted) ? "  <-- predicted" : "");
    }

    /* ---- Python reference (embed for easy comparison) ---- */
    printf("\nPython reference prediction: 0\n");
    printf("%s: %s\n",
           (predicted == 0) ? "PASS" : "FAIL",
           (predicted == 0)
               ? "C and Python models agree!"
               : "MISMATCH — C and Python predictions differ");

    return (predicted == 0) ? 0 : 1;
}
