/*
 * bitnet_inference.c — auto-generated by export_bitnet.py
 *
 * Ternary BitNet forward pass in ANSI C.
 * No dynamic allocation; works on bare-metal microcontrollers (ESP32, etc.).
 *
 * Compile with:
 *   gcc -Wall -O2 -std=c99 -c bitnet_inference.c -lm
 */

#include "bitnet_inference.h"
#include "bitnet_weights.h"
#include <math.h>
#include <string.h>

/* ---------------------------------------------------------------------------
 * ternary_matmul_add_bias
 *   Computes:  out[i] = scale * sum(weights[i*in_size + j] * in[j]) + bias[i]
 *   weights values are in {-1, 0, +1}, so multiply is add/subtract.
 * --------------------------------------------------------------------------- */
static void ternary_matmul_add_bias(
    const int8_t * restrict weights,  /* [out_size * in_size] row-major */
    float                   scale,
    const float  * restrict bias,     /* [out_size] */
    const float  * restrict in,       /* [in_size]  */
    float        * restrict out,      /* [out_size] */
    int in_size,
    int out_size)
{
    for (int i = 0; i < out_size; ++i) {
        float acc = 0.0f;
        const int8_t *row = weights + (size_t)i * in_size;
        for (int j = 0; j < in_size; ++j) {
            int8_t w = row[j];
            if (w == 1)       acc += in[j];
            else if (w == -1) acc -= in[j];
            /* w == 0: skip */
        }
        out[i] = acc * scale + bias[i];
    }
}

/* ---------------------------------------------------------------------------
 * relu_inplace — apply ReLU in-place: x = max(0, x)
 * --------------------------------------------------------------------------- */
static void relu_inplace(float *x, int n)
{
    for (int i = 0; i < n; ++i)
        if (x[i] < 0.0f) x[i] = 0.0f;
}

/* ---------------------------------------------------------------------------
 * softmax_inplace — numerically stable softmax in-place
 * --------------------------------------------------------------------------- */
void softmax_inplace(float *x, int n)
{
    /* find max for numerical stability */
    float mx = x[0];
    for (int i = 1; i < n; ++i)
        if (x[i] > mx) mx = x[i];

    float sum = 0.0f;
    for (int i = 0; i < n; ++i) {
        x[i] = expf(x[i] - mx);
        sum += x[i];
    }
    for (int i = 0; i < n; ++i)
        x[i] /= sum;
}

/* ---------------------------------------------------------------------------
 * bitnet_forward
 *
 *   Runs the full [27 → 64 → 37] BitNet forward pass.
 *
 *   input  : float array of length INPUT_SIZE  (caller provides)
 *   output : float array of length OUTPUT_SIZE (caller provides, filled on return)
 *
 *   After return, output[i] holds the probability for class i.
 *   argmax(output) gives the predicted class index.
 * --------------------------------------------------------------------------- */
void bitnet_forward(const float *input, float *output)
{
    /* Hidden layer activation buffer */
    float hidden[HIDDEN_SIZE];

    /* Layer 0: input → hidden */
    ternary_matmul_add_bias(
        layer0_weights, scales[0], layer0_biases,
        input, hidden,
        INPUT_SIZE, HIDDEN_SIZE);
    relu_inplace(hidden, HIDDEN_SIZE);

    /* Layer 1: hidden → output logits */
    ternary_matmul_add_bias(
        layer1_weights, scales[1], layer1_biases,
        hidden, output,
        HIDDEN_SIZE, OUTPUT_SIZE);

    /* Apply softmax to get probabilities */
    softmax_inplace(output, OUTPUT_SIZE);
}

/* ---------------------------------------------------------------------------
 * bitnet_argmax — returns index of maximum value in array of length n
 * --------------------------------------------------------------------------- */
int bitnet_argmax(const float *x, int n)
{
    int best = 0;
    for (int i = 1; i < n; ++i)
        if (x[i] > x[best]) best = i;
    return best;
}
