/*
 * bitnet_inference.h — BitNet inference API
 * auto-generated by export_bitnet.py
 */

#ifndef BITNET_INFERENCE_H
#define BITNET_INFERENCE_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * bitnet_forward — run the full [27→64→37] BitNet forward pass.
 *
 * @param input   float array of length INPUT_SIZE
 * @param output  float array of length OUTPUT_SIZE (filled with probabilities)
 */
void bitnet_forward(const float *input, float *output);

/**
 * softmax_inplace — apply softmax to array x of length n, in-place.
 */
void softmax_inplace(float *x, int n);

/**
 * bitnet_argmax — return index of maximum value in array x of length n.
 */
int bitnet_argmax(const float *x, int n);

#ifdef __cplusplus
}
#endif

#endif /* BITNET_INFERENCE_H */
